### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cavarzan**
Fixed typos, removed invalid links and references to bootstrap material design

### CODE REVIEW

**Comment by cavarzan** [comment]
@moifort can I close this?

**Comment by moifort** [comment]
👍 👍 Thanks for the PR @cavarzan !!

**Comment by pascalgrimaud** [comment]
wahou @moifort is back ? :p

**Comment by moifort** [comment]
@pascalgrimaud I am not dead! :D

**Comment by pascalgrimaud** [comment]
happy to see you here!
Hope everything is ok for you, and sorry for spamming :)
:kiss:

**Comment by moifort** [comment]
No problem! Thanks to maintain my old projects! 👍

**Pull request merged**
